services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: reetro_postgres_application
    container_name: reetro_postgres_application
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.env
    ports:
      - "5400:5432"

  redis:
    image: redis:6-alpine
    container_name: reetro_redis_application
    ports:
      - "6379:6379"
    depends_on:
      - postgres

  golang:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    image: reetro_golang_application
    container_name: reetro_golang_application
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.env
    ports:
      - "8080:8080"

volumes:
  postgres_data: {}
  postgres_data_backups: {}
