CREATE TABLE users (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255),
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    user_type VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE boards (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    template VARCHAR(100) NOT NULL,
    columns TEXT[] NOT NULL,
    created_by_id VARCHAR(36),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    modified_by_id VARCHAR(36),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);